services:
  client:
    build:
      context: client
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
      - fastapi

  server:
    build:
      context: server
      dockerfile: dockerfile
    ports:
      - "4000:4000"

  fastapi:
    build:
      context: server
      dockerfile: Dockerfile.fastapi
    ports:
      - "5000:5000"
