FROM python:3.10

WORKDIR /app

COPY songs_api.py .
COPY import_songs.py .
COPY karaoke.csv .
COPY karaoke.db .

RUN pip install fastapi uvicorn yt-dlp

EXPOSE 5000

CMD ["uvicorn", "songs_api:app", "--host", "0.0.0.0", "--port", "5000"]
